# This is a basic workflow to help you get started with Actions

name: Docker Dragonflydb CI

# Controls when the workflow will run
on:
  schedule:
  - cron: "0 16 * * *"

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:                # Job-level permissions configuration starts here
      contents: write           # 'write' access to repository contents
      pull-requests: write      # 'write' access to pull requests

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'
      - name: Run Java Program and Save Output
        id: java-run
        run: |
          echo "version=$(java -jar ./dragonflydb/dragonflydb-schdule.jar)" >> $GITHUB_OUTPUT

      - if: ${{ success() && steps.java-run.outputs.version != '' }}
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - if: ${{ success() && steps.java-run.outputs.version != '' }}
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - if: ${{ success() && steps.java-run.outputs.version != '' }}
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - if: ${{ success() && steps.java-run.outputs.version != '' }}
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./dragonflydb
          push: true
          platforms: linux/amd64,linux/arm64/v8
          tags: dph5199278/dragonflydb:${{ steps.java-run.outputs.version }},dph5199278/dragonflydb:latest
      - if: ${{ success() && steps.java-run.outputs.version != '' }}
        name: Change version
        run: |
          echo "${{ steps.java-run.outputs.version }}" > ./dragonflydb/version.txt
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "docs: version to ${{ steps.java-run.outputs.version }}"
      - if: ${{ success() && steps.java-run.outputs.version != '' }}
        name: Push version
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          branch: ${{ github.ref }}
